### ISSUE TITLE
Deploy to Nuget 

### ISSUE THREAD

**Issue by kiran94** [flq/neocaster#1]
Would it be possible to deploy this library to Nuget? I think that this would ease integration of the logic here into existing projects. 

Briefly looking at the project, I think you will just need to add some additional tags to the `csproj` like `version `, `description` etc and possibly could use this opportunity to also upgrade to the latest .NET standard?

**Comment by flq** [comment]
Hello Kiran,
I haven’t touched this project for quite some time. Do you think that what is available is useful at all?

**Comment by kiran94** [comment]
Yes I think so, since opening this issue I have found some alternative neo4j ORMs like 
- https://github.com/barnardos-au/Neo4jMapper
- https://github.com/francnuec/Neo4jClient.DataAnnotations

But I liked the Dapper inspired syntax here since I already use that library and really enjoy the simplicity. I can see this project has not been maintained in a while so I can understand if it is not a priority anymore.

Thanks,
Kiran
